version: '3.9'
services:
  postgres_db:
    image: postgres:latest
    container_name: Postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      databases_network:
        ipv4_address: ${POSTGRES_IPV4}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data


volumes:
  postgres_db:
    name: ${POSTGRES_DB_VOL}

