version: '3.9'
services:
  postgres_db:
    image: postgres:latest
    container_name: Postgres
    restart: always
    network_mode: "host"  # <--- ZMIANA KLUCZOWA
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_db:/var/lib/postgresql/data


volumes:
  postgres_db:
    name: ${POSTGRES_DB_VOL}

